backend:
  name: github
  repo: TON-USERNAME/atlas-plantes-grand-sud-haiti   # ← Remplace TON-USERNAME par ton vrai nom GitHub

media_folder: "uploads/plants"
public_folder: "/uploads/plants"

collections:
  - name: "plantes"
    label: "🌿 Plantes"
    folder: "data"
    create: true
    slug: "{{fields.id_plante}}"
    fields:
      - {label: "ID Plante", name: "id_plante", widget: "string"}
      - {label: "Nom scientifique", name: "nom_scientifique", widget: "string", required: true}
      - {label: "Nom créole", name: "nom_creole", widget: "string"}
      - {label: "Famille", name: "famille_fr", widget: "string"}
      - {label: "Usage Haïti", name: "usage_haiti", widget: "text"}
      - {label: "Toxique ?", name: "toxique", widget: "boolean"}
      - {label: "Lien PubMed", name: "lien_pubmed", widget: "string"}
      - {label: "Lien GBIF", name: "lien_gen", widget: "string"}
